# Enables the "Sponsor" button on the repository.
buy_me_a_coffee: tonytonycoder
ko_fi: tonytonycoder
custom: ["https://www.paypal.com/paypalme/nacode11"]

# GitHub Sponsors — uncomment once you've joined https://github.com/sponsors:
# github: tonytonycoder11
